dist: trusty
language: node_js
node_js:
  - '6'
before_script:
  - npm install -g web-component-tester
  - gulp build:tests
script: xvfb-run wct
cache: yarn
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
